// <auto-generated />
namespace Gießformkonfigurator.WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intialafterprojectmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialafterprojectmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202109081001119_intial after project migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
