//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gießformkonfigurator.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolzen
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int SAP_Nr_ { get; set; }
        public string Bezeichnung_RoCon { get; set; }
        public decimal Hoehe { get; set; }
        public decimal Außendurchmesser { get; set; }
        public decimal Gießhoehe_Max { get; set; }
        public bool mit_Gewinde { get; set; }
        public Nullable<decimal> Gewinde { get; set; }
        public bool mit_Steckbolzen { get; set; }
        public Nullable<decimal> Hoehe_Fuehrung { get; set; }
        public Nullable<decimal> Außendurchmesser_Fuehrung { get; set; }
    }
}
