//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gießformkonfigurator.WindowsForms
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Grundplatte
    {
        [Key]
        public int SAP_Nr_ { get; set; }
        public string Bezeichnung_RoCon { get; set; }
        public decimal Außendurchmesser { get; set; }
        public decimal Hoehe { get; set; }
        public decimal Konus_Außen_Max { get; set; }
        public decimal Konus_Außen_Min { get; set; }
        public decimal Konus_Außen_Winkel { get; set; }
        public decimal Konus_Hoehe { get; set; }
        public bool mit_Konusfuehrung { get; set; }
        public Nullable<decimal> Konus_Innen_Max { get; set; }
        public Nullable<decimal> Konus_Innen_Min { get; set; }
        public Nullable<decimal> Konus_Innen_Winkel { get; set; }
        public bool mit_Lochfuehrung { get; set; }
        public Nullable<decimal> Innendurchmesser { get; set; }
        public string Toleranz_Innendurchmesser { get; set; }
        public bool mit_Kern { get; set; }
    
        //public virtual Lochkreis Lochkreis { get; set; }
    }
}
