//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gießformkonfigurator.WindowsForms
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Innenkern
    {
        [Key]
        public int SAP_Nr_ { get; set; }
        public string Bezeichnung_RoCon { get; set; }
        public decimal Außendurchmesser { get; set; }
        public string Toleranz_Außendurchmesser { get; set; }
        public decimal Hoehe { get; set; }
        public decimal Gießhoehe_Max { get; set; }
        public bool mit_Konusfuehrung { get; set; }
        public Nullable<decimal> Konus_Außen_Max { get; set; }
        public Nullable<decimal> Konus_Außen_Min { get; set; }
        public Nullable<decimal> Konus_Außen_Winkel { get; set; }
        public Nullable<decimal> Konus_Hoehe { get; set; }
        public bool mit_Fuehrungsstift { get; set; }
        public Nullable<decimal> Hoehe_Fuehrung { get; set; }
        public Nullable<decimal> Durchmesser_Fuehrung { get; set; }
        public Nullable<decimal> Toleranz_Durchmesser_Fuehrung { get; set; }
        public bool mit_Lochfuehrung { get; set; }
        public Nullable<decimal> Durchmesser_Adapter { get; set; }
    }
}
