//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gießformkonfigurator.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lochkreis
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int SAP_Nr_ { get; set; }
        public int LK_Nr_ { get; set; }
        public int Anzahl_Bohrungen { get; set; }
        public string Gewinde { get; set; }
        public Nullable<decimal> Form { get; set; }
    
        //public virtual Einlegeplatte Einlegeplatte { get; set; }
        //public virtual Grundplatte Grundplatte { get; set; }
    }
}
