//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gießformkonfigurator.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktCup
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int SAP_Nr_ { get; set; }
        public string Grund_Cup { get; set; }
        public decimal Innendurchmesser { get; set; }
        public string LK { get; set; }
    }
}
