//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gießformkonfigurator.WindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ring
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int SAP_Nr_ { get; set; }
        public string Bezeichnung_RoCon { get; set; }
        public decimal Außendurchmesser { get; set; }
        public Nullable<decimal> Toleranz_Außendurchmesser { get; set; }
        public decimal Innendurchmesser { get; set; }
        public string Toleranz_Innendurchmesser { get; set; }
        public decimal Hoehe { get; set; }
        public decimal Gießhoehe_Max { get; set; }
        public bool mit_Konusfuehrung { get; set; }
        public Nullable<decimal> Konus_Max { get; set; }
        public Nullable<decimal> Konus_Min { get; set; }
        public Nullable<decimal> Konus_Winkel { get; set; }
        public Nullable<decimal> Konus_Hoehe { get; set; }
        public bool ohne_Konusfuehrung { get; set; }
    }
}
