// <auto-generated />
namespace Gießformkonfigurator.WindowsForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NeueAttributeProductDisc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NeueAttributeProductDisc));
        
        string IMigrationMetadata.Id
        {
            get { return "202108091114427_Neue Attribute ProductDisc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
